FROM ubuntu:20.04

RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip python-is-python3 git graphviz
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-8-jre
RUN pip install pyspark==3.3.1
RUN pip install graphviz jupyterlab
RUN pip install pyrecdp --pre